name: Build Swift Project

inputs:
  checkout-scheme:
    description: The schema passed to utils/update-checkout
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: brew install ninja sccache
    - uses: actions/checkout@v4
      with:
        repository: swiftlang/swift
        path: swift-project/swift
    - name: Update checkout
      run: utils/update-checkout --clone --scheme $CHECKOUT_SCHEME
      working-directory: ./swift-project/swift
      env:
        CHECKOUT_SCHEME: ${{ inputs.checkout-scheme }}
    - name: Build toolchain
      run: |
        utils/build-script --skip-build-benchmarks \
          --swift-darwin-supported-archs "$(uname -m)" \
          --release --swift-disable-dead-stripping \
          --bootstrapping=hosttools \
          --skip-build
      working-directory: ./swift-project/swift
    - name: Build llvm
      run: |
        ninja -C ../build/Ninja-ReleaseAssert/llvm-macosx-arm64
      working-directory: ./swift-project/swift
    - name: Build cmark
      run: |
        ninja -C ../build/Ninja-ReleaseAssert/cmark-macosx-arm64
      working-directory: ./swift-project/swift
    - name: Build swift-frontend
      run: |
        ninja -C ../build/Ninja-ReleaseAssert/swift-macosx-arm64 swift-frontend
      working-directory: ./swift-project/swift
    - name: Create symbolic links to build directories
      run: |
        mkdir -p build/Default
        ln -s ../Ninja-ReleaseAssert/swift-macosx-arm64 build/Default/swift
        ln -s ../Ninja-ReleaseAssert/llvm-macosx-arm64 build/Default/llvm
      working-directory: ./swift-project
