name: Build Swift Project

inputs:
  checkout-scheme:
    description: The schema passed to utils/update-checkout
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: swiftlang/swift
        path: swift-project/swift
    - name: Install dependencies
      run: brew install ninja sccache
      shell: bash
    - name: Update checkout
      run: |
        utils/update-checkout --clone --scheme $CHECKOUT_SCHEME \
          --skip-history \
          --skip-repository brotli \
          --skip-repository cmake \
          --skip-repository cmark \
          --skip-repository curl \
          --skip-repository icu \
          --skip-repository indexstore-db \
          --skip-repository libxml2 \
          --skip-repository llbuild \
          --skip-repository mimalloc \
          --skip-repository ninja \
          --skip-repository sourcekit-lsp \
          --skip-repository swift-argument-parser \
          --skip-repository swift-asn1 \
          --skip-repository swift-async-algorithms \
          --skip-repository swift-atomics \
          --skip-repository swift-build \
          --skip-repository swift-certificates \
          --skip-repository swift-cmark-gfm \
          --skip-repository swift-collections \
          --skip-repository swift-corelibs-blocksruntime \
          --skip-repository swift-corelibs-foundation \
          --skip-repository swift-corelibs-libdispatch \
          --skip-repository swift-corelibs-xctest \
          --skip-repository swift-crypto \
          --skip-repository swift-docc \
          --skip-repository swift-docc-render-artifact \
          --skip-repository swift-docc-symbolkit \
          --skip-repository swift-driver \
          --skip-repository swift-experimental-string-processing \
          --skip-repository swift-format \
          --skip-repository swift-foundation \
          --skip-repository swift-foundation-icu \
          --skip-repository swift-installer-scripts \
          --skip-repository swift-integration-tests \
          --skip-repository swift-llvm-bindings \
          --skip-repository swift-lmdb \
          --skip-repository swift-log \
          --skip-repository swift-markdown \
          --skip-repository swift-nio \
          --skip-repository swift-nio-ssl \
          --skip-repository swift-numerics \
          --skip-repository swift-sdk-generator \
          --skip-repository swift-stress-tester \
          --skip-repository swift-subprocess \
          --skip-repository swift-syntax \
          --skip-repository swift-system \
          --skip-repository swift-testing \
          --skip-repository swift-toolchain-sqlite \
          --skip-repository swift-tools-protocols \
          --skip-repository swift-tools-support-core \
          --skip-repository swift-xcode-playground-support \
          --skip-repository swiftpm \
          --skip-repository wasi-libc \
          --skip-repository wasmkit \
          --skip-repository yams \
          --skip-repository zlib
      shell: bash
      working-directory: ./swift-project/swift
      env:
        CHECKOUT_SCHEME: ${{ inputs.checkout-scheme }}
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
    - name: Build Swift
      run: |
        utils/build-script --skip-build-benchmarks \
          --swift-darwin-supported-archs "$(uname -m)" \
          --release --swift-disable-dead-stripping \
          --bootstrapping=hosttools \
          --skip-build \
          --skip-early-swift-driver \
          --skip-build-cmark \
          --skip-build-llvm \
          --skip-build-swift \
          --sccache
        ninja -C ../build/Ninja-ReleaseAssert/llvm-macosx-arm64 include/llvm/all
        ninja -C ../build/Ninja-ReleaseAssert/swift-macosx-arm64 include/swift/all
      shell: bash
      working-directory: ./swift-project/swift
      env:
        SCCACHE_GHA_ENABLED: "true"
    - name: Create symbolic links to build directories
      run: |
        mkdir -p build/Default
        ln -s ../Ninja-ReleaseAssert/swift-macosx-arm64 build/Default/swift
        ln -s ../Ninja-ReleaseAssert/llvm-macosx-arm64 build/Default/llvm
      shell: bash
      working-directory: ./swift-project
