name: Checkout Swift Headers
description: |
  This action checks-out certain header files from the swiftlang/swift
  repository.

inputs:
  path:
    description: Relative path under $GITHUB_WORKSPACE to place the repository
    required: true
  swift-version-major:
    description: The Swift toolchain major version.
    required: true
  swift-version-minor:
    description: The Swift toolchain minor version.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: swiftlang/swift
        path: ${{ inputs.path }}
        ref: release/${{ inputs.swift-version-major }}.${{ inputs.swift-version-minor }}
        sparse-checkout: |
          include/swift
          stdlib/include
          stdlib/public/SwiftShims
          stdlib/public/runtime/MetadataAllocatorTags.def
    - name: Write CMakeConfig.h file
      run: |
        cat > include/swift/Runtime/CMakeConfig.h << EOF
        #ifndef SWIFT_RUNTIME_CMAKECONFIG_H
        #define SWIFT_RUNTIME_CMAKECONFIG_H
        #define SWIFT_VERSION_MAJOR "${SWIFT_VERSION_MAJOR}"
        #define SWIFT_VERSION_MINOR "${SWIFT_VERSION_MINOR}"
        #endif
        EOF
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        SWIFT_VERSION_MAJOR: ${{ inputs.swift-version-major }}
        SWIFT_VERSION_MINOR: ${{ inputs.swift-version-minor }}
